---
run_params:
  n_runs: 25
  n_epochs: 50
  n_steps: 30000
  n_episodes_test: 10
env_params:
  name: Gym.AntBulletEnv-v0
  params:
    horizon: 1000
    gamma: 0.99
agent_params:
  A2C:
    actor_lr: 7.0e-4
    critic_lr: 7.0e-4
  TRPO:
    max_kl: 1.0e-2
    critic_lr: 3.0e-3
    n_steps_per_fit: 3000
  PPO:
    actor_lr: 3.0e-4
    critic_lr: 3.0e-4
  DDPG:
    actor_lr: 1.0e-4
    critic_lr: 1.0e-3
    batch_size: 128
    initial_replay_size: 5000
    max_replay_size: 1000000
    n_features: [ 400, 300 ]
  TD3:
    actor_lr: 1.0e-4
    critic_lr: 1.0e-3
    batch_size: 128
    initial_replay_size: 5000
    max_replay_size: 1000000
    n_features: [400, 300]
  SAC:
    actor_lr: 5.0e-5
    critic_lr: 3.0e-4
    warmup_transitions: 10000
    initial_replay_size: 5000
    max_replay_size: 500000
    
