%YAML 1.2
---
run_params:
  n_runs: 25
  n_epochs: 100
  n_steps: 100
  n_steps_test: 1000
env_params:
  name: GridWorld
  params:
    height: 10
    width: 10
    goal: [8, 7]

agent_params:
  QLearning:
    learning_rate: 1.
    epsilon: 1.
    decay_lr: .8
    decay_eps: .5
    epsilon_test: 0.
  QLambda:
    learning_rate: 1.
    epsilon: 1.
    decay_lr: .8
    decay_eps: .5
    epsilon_test: 0.
  DoubleQLearning:
    learning_rate: 1.
    epsilon: 1.
    decay_lr: .8
    decay_eps: .5
    epsilon_test: 0.
  SpeedyQLearning:
    learning_rate: 1.
    epsilon: 1.
    decay_lr: .8
    decay_eps: .5
    epsilon_test: 0.
  WeightedQLearning:
    learning_rate: 1.
    epsilon: 1.
    decay_lr: .8
    decay_eps: .5
    epsilon_test: 0.
  SARSA:
    learning_rate: 1.
    epsilon: 1.
    decay_lr: .8
    decay_eps: .5
    epsilon_test: 0.
  SARSALambda:
    learning_rate: 1.
    epsilon: 1.
    decay_lr: .8
    decay_eps: .5
    epsilon_test: 0.
