%YAML 1.2
---
run_params:
  n_epochs: 25
  n_steps: 30000
  n_episodes_test: 10
env_params:
  name: Gym.LunarLanderContinuous-v2
  params:
    horizon: 1000
    gamma: 0.99
agent_params:
  A2C:
    actor_lr: 7.0e-4
    critic_lr: 7.0e-4
    preprocessors: StandardizationPreprocessor
  TRPO:
    max_kl: 1.0e-2
    critic_lr: 3.0e-2
    n_steps_per_fit: 3000
    preprocessors: StandardizationPreprocessor
  PPO:
    actor_lr: 3.0e-4
    critic_lr: 3.0e-3
    preprocessors: StandardizationPreprocessor
  DDPG:
    actor_lr: 1.0e-4
    critic_lr: 1.0e-3
    n_features: [64, 64]
    initial_replay_size: 128
    max_replay_size: 1000000
    tau: 1.0e-3
    batch_size: 64
  TD3:
    actor_lr: 1.0e-4
    critic_lr: 1.0e-3
    n_features: [64, 64]
    initial_replay_size: 128
    max_replay_size: 1000000
    tau: 1.0e-3
    batch_size: 64
  SAC:
    actor_lr: 1.0e-4
    critic_lr: 3.0e-4
    warmup_transitions: 128
    initial_replay_size: 128
    max_replay_size: 500000
    n_features: 64
    batch_size: 64
    tau: 5.0e-3
    lr_alpha: 3.0e-4
